version: "3"

# a couple of services that are generaly useful, remember to set up your .env file first 
services:
  # Overview
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ${DATADIR}/homepage:/app/config # Make sure your local config directory exists
      # - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID
      PGID: $PGID
  # heimdall:
  #   image: linuxserver/heimdall
  #   container_name: heimdall
  #   restart: unless-stopped
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${DATADIR}/heimdall:/config
  #   ports:
  #     - 9080:80
  #     - 9443:443

  # adblocker
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "3300:3000/tcp"
      - "3380:80/tcp"
    volumes:
       - '${DATADIR}/adguard/workdir:/opt/adguardhome/work'
       - '${DATADIR}/adguard/confdir:/opt/adguardhome/conf'
    cap_add:
      - NET_ADMIN
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"


  # WIFI hotspot
  # unifi-controller:
  #   image: ghcr.io/linuxserver/unifi-controller:arm32v7-latest
  #   container_name: unifi-controller
  #   restart: unless-stopped
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - MEM_LIMIT=512M #optional
  #   volumes:
  #     - ${DATADIR}/unifi-controller:/config
  #   ports:
  #     - 3478:3478/udp
  #     - 10001:10001/udp
  #     - 8080:8080
  #     - 8443:8443
  #     - 1900:1900/udp
  #     - 8843:8843
  #     - 8880:8880
  #     - 6789:6789
  #     - 5514:5514
  #   labels: # better keep this one up to date manually
  #     - "com.centurylinklabs.watchtower.enable=false"
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: "http://localhost:3100/loki/api/v1/push"
  #       max-size: "200m"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true # deleting old unused images automatically
      # optional for notifications
      #- WATCHTOWER_NOTIFICATIONS=email
      #- WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
      #- WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}
      # alternative for notification via pushover
      #- WATCHTOWER_NOTIFICATIONS=shoutrrr
      #- WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:${PO_TOKEN}@${PO_USERKEY}
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"

  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ${DATADIR}/loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ${DATADIR}/loki/data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        max-size: "200m"


  # duplicati:
  #   image: lscr.io/linuxserver/duplicati:2.0.6
  #   container_name: duplicati
  #   restart: unless-stopped
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     #- CLI_ARGS= #optional
  #   volumes:
  #     - ${DATADIR}/duplicati/config>:/config
  #     - ${DATADIR}:/source
  #   ports:
  #     - 8200:8200
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: "http://localhost:3100/loki/api/v1/push"
  #       max-size: "200m"
